services:
  db:
    container_name: postgres
    image: postgis/postgis:18-3.6
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Rome
    volumes: 
      - ./backend/src/db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    build: .
    env_file:
      - .env
    ports:
      - ${APP_PORT}:3000